version: "3.9"

services:
  playground:
    image: "192.168.99.115/data-warehouse/business-sub-system:latest"
    container_name: "dwd-business-sub-system"
    restart: "always"
    network_mode: "host"