# ----------------------------------------------------------------------------------------------------------------------
# 核心配置
# ----------------------------------------------------------------------------------------------------------------------
carnival:
  id:
    enabled: true
    algorithm: snowflake_string
    snowflake:
      data-center-id: 0
      worker-id: 0
      length: 36
      pad-character: '0'
